env:
  CIRRUS_CLONE_SUBMODULES: true
  DEBIAN_FRONTEND: noninteractive
  LANG: C
  PGVERSION: 14
  CIRRUS_LOG_TIMESTAMP: true

task:
  name: Formatting checks & linting
  container:
    image: ubuntu:22.04
  setup_script:
    - apt-get update
    - apt-get install -y python3 python3-pip cmake curl
  pip_script: pip install -r dev_requirements.txt
  build_script:
    - touch config.mak # Fake that configure has run
  test_script:
    - make format-check
    - make lint
